# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  host: db
#  username: postgres
#  password:


#development:
#  <<: *default
#  database: app_development

#test:
#  <<: *default
#  database: app_test

#production:
#  <<: *default
#  database: app_production
#  username: app
#  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>


default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: landscape_sns_development

test:
  <<: *default
  database: landscape_sns_test

production:
  <<: *default
  database: landscape_sns_production
  username: landscape_sns
  password: <%= ENV[' LANDSCAPE_SNS_DATABASE_PASSWORD'] %>
